<?php

declare(strict_types=1);

namespace App\Livewire\Concerns;

use App\Enums\SaleStatus;
use App\Models\Branch;
use App\Models\Product;
use App\Models\Sale;
use App\Models\User;
use App\Services\StockService;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * Shared Dashboard Data Loading Logic
 *
 * This trait consolidates the dashboard data loading methods
 * used by both Index.php and CustomizableDashboard.php
 * to eliminate code duplication and ensure consistency.
 *
 * SECURITY (V40-SQL-04): SQL Expression Safety - REVIEWED
 * ========================================================
 * This trait uses selectRaw(), whereRaw(), and orderByRaw() with variable interpolation.
 * All interpolated values are SAFE because they come from validated sources:
 *
 * 1. $stockExpr variable: Generated by StockService::get*StockCalculationExpression()
 *    - Validates column names via regex: /^[a-zA-Z_][a-zA-Z0-9_]*(\.[a-zA-Z_][a-zA-Z0-9_]*)?$/
 *    - Throws InvalidArgumentException on invalid input
 *
 * 2. CASE expressions: Use only hardcoded column names (min_stock, products.id, etc.)
 *    combined with the validated $stockExpr. No user input is ever interpolated.
 *
 * 3. $branchId parameter: Type-checked integer from session/authenticated user,
 *    validated by StockService as positive integer before SQL generation.
 *
 * @security-reviewed V40 - SQL expressions validated via StockService regex validation
 */
trait LoadsDashboardData
{
    protected int $cacheTtl = 300;

    protected ?int $branchId = null;

    protected bool $isAdmin = false;

    /**
     * Dashboard data loading errors (non-fatal)
     *
     * When any widget query fails, we record the error and fall back to safe defaults
     * instead of crashing the whole dashboard with a 500.
     */
    public array $dashboardErrors = [];

    public bool $dashboardHasErrors = false;

    /**
     * Initialize dashboard context
     */
    protected function initializeDashboardContext(): void
    {
        $user = auth()->user();
        if (! $user) {
            abort(403);
        }

        $this->branchId = current_branch_id();

        // Fall back to the user's own branch when no context is set
        if (! $this->branchId && $user->branch_id) {
            $this->branchId = (int) $user->branch_id;
        }

        // Use case-insensitive role check - seeder uses "Super Admin" (Title Case)
        $this->isAdmin = $user->hasAnyRole(['Super Admin', 'super-admin', 'Admin', 'admin']);
        $ttl = null;
        try {
            $ttl = \App\Models\SystemSetting::where('setting_key', 'advanced.cache_ttl')->value('value');
        } catch (\Throwable) {
            // If settings table isn't ready or query fails, fall back safely.
            $ttl = null;
        }

        $this->cacheTtl = (int) ($ttl ?? 300);
    }

    /**
     * Get cache key prefix for current context
     */
    protected function getCachePrefix(): string
    {
        // Include optional period (if the consuming component supports it) to avoid
        // stale chart caches when users switch between different dashboard periods.
        $period = 'default';
        if (property_exists($this, 'selectedPeriod')) {
            $value = (string) ($this->selectedPeriod ?? 'default');
            $period = in_array($value, ['today', 'week', 'month'], true) ? $value : 'default';
        }

        return "dashboard:branch_".($this->branchId ?? 'all').":admin_{$this->isAdmin}:period_{$period}";
    }

    /**
     * Scope query to current branch context
     */
    protected function scopeQueryToBranch($query)
    {
        // If a branch context is active, always scope to it (including for admins).
        if ($this->branchId) {
            return $query->where('branch_id', $this->branchId);
        }

        return $query;
    }


    /**
     * Record a non-fatal dashboard error and keep rendering with safe defaults.
     *
     * We intentionally avoid throwing here, because the dashboard is a *read-only* overview.
     * A single widget query failing should not take down the whole page.
     */
    protected function recordDashboardError(string $context, \Throwable $e): void
    {
        $this->dashboardHasErrors = true;

        $this->dashboardErrors[] = [
            'context' => $context,
            'message' => config('app.debug') ? $e->getMessage() : __('Something went wrong while loading dashboard data.'),
        ];

        // Best-effort logging (never crash the UI because logging failed)
        try {
            Log::error('Dashboard data load error', [
                'context' => $context,
                'branch_id' => $this->branchId,
                'is_admin' => $this->isAdmin,
                'user_id' => auth()->id(),
                'error' => $e->getMessage(),
            ]);
        } catch (\Throwable) {
            // ignore
        }
    }

    /**
     * Refresh all dashboard data (clear cache and reload)
     */
    protected function refreshDashboardData(): void
    {
        $prefix = $this->getCachePrefix();
        Cache::forget("{$prefix}:stats");
        Cache::forget("{$prefix}:chart_data");
        Cache::forget("{$prefix}:low_stock");
        Cache::forget("{$prefix}:recent_sales");
        Cache::forget("{$prefix}:trends");

        $this->loadDashboardStats();
        $this->loadChartData();
        $this->loadLowStockProducts();
        $this->loadRecentSales();
        $this->loadTrendIndicators();
    }

    /**
     * Load all dashboard data
     */
    protected function loadAllDashboardData(): void
    {
        $this->loadDashboardStats();
        $this->loadChartData();
        $this->loadLowStockProducts();
        $this->loadRecentSales();
        $this->loadTrendIndicators();
    }

    /**
     * Load main statistics
     */
    protected function loadDashboardStats(): void
    {
        $cacheKey = "{$this->getCachePrefix()}:stats";

        try {
            $this->stats = Cache::remember($cacheKey, $this->cacheTtl, function () {
                $today = now()->startOfDay();
                $startOfMonth = now()->startOfMonth();

                $salesQuery = $this->scopeQueryToBranch(Sale::query());
                $productsQuery = $this->scopeQueryToBranch(Product::query());

                // V30-CRIT-01 FIX: Use sale_date (business date) instead of created_at
                // This ensures synced/backdated sales appear on the correct business day
                return [
                    'today_sales' => number_format(
                        (clone $salesQuery)->whereDate('sale_date', $today)->sum('total_amount') ?? 0,
                        2
                    ),
                    'month_sales' => number_format(
                        (clone $salesQuery)->where('sale_date', '>=', $startOfMonth)->sum('total_amount') ?? 0,
                        2
                    ),
                    'open_invoices' => (clone $salesQuery)
                        ->whereNotIn('status', SaleStatus::nonRevenueStatuses())
                        ->where(function ($q) {
                            $q->whereNull('payment_status')
                                ->orWhere('payment_status', '!=', 'paid');
                        })
                        ->count(),
                    'active_branches' => $this->isAdmin ? Branch::where('is_active', true)->count() : 1,
                    'active_users' => $this->isAdmin
                        ? User::where('is_active', true)->count()
                        : User::where('is_active', true)->where('branch_id', $this->branchId)->count(),
                    'total_products' => (clone $productsQuery)->count(),
                    'low_stock_count' => $this->calculateLowStockCount($productsQuery),
                ];
            });
        } catch (\Throwable $e) {
            $this->recordDashboardError('stats', $e);

            $this->stats = [
                'today_sales' => '0.00',
                'month_sales' => '0.00',
                'open_invoices' => 0,
                'active_branches' => $this->isAdmin ? 0 : 1,
                'active_users' => 0,
                'total_products' => 0,
                'low_stock_count' => 0,
            ];
        }
    }

    /**
     * Calculate low stock count using optimized query
     * V27-CRIT-01 FIX: Use branch-scoped stock calculation instead of global
     *
     * SECURITY NOTE: The $stockExpr is generated by StockService::get*StockCalculationExpression()
     * which validates all column names against SQL injection using regex patterns.
     * See StockService for the validation logic.
     */
    protected function calculateLowStockCount($productsQuery): int
    {
        // V27-CRIT-01 FIX: Use branch-scoped stock calculation when branch context is available
        // SECURITY: StockService validates column names with regex before interpolation
        // @security-reviewed V43 - $stockExpr is validated by StockService regex patterns
        $stockExpr = $this->branchId
            ? StockService::getBranchStockCalculationExpression('products.id', $this->branchId)
            : StockService::getStockCalculationExpression();

        // @phpstan-ignore-next-line - $stockExpr is regex-validated by StockService
        return (clone $productsQuery)
            ->whereNotNull('min_stock')
            ->where('min_stock', '>', 0)
            ->whereRaw("{$stockExpr} <= min_stock")
            ->count();
    }

    /**
     * Load chart data with optimized single query for inventory stats
     */
    protected function loadChartData(): void
    {
        $cacheKey = "{$this->getCachePrefix()}:chart_data";

        $fallback = [
            'sales' => ['labels' => [], 'data' => [], 'total' => '0.00'],
            'payment' => ['labels' => [], 'data' => [], 'totals' => []],
            'inventory' => ['in_stock' => 0, 'low_stock' => 0, 'out_of_stock' => 0],
        ];

        try {
            $chartData = Cache::remember($cacheKey, $this->cacheTtl, function () use ($fallback) {
                // Sales chart data
                $salesData = $fallback['sales'];
                try {
                    $salesData = $this->buildSalesChartData();
                } catch (\Throwable $e) {
                    $this->recordDashboardError('sales_chart', $e);
                }

                // Payment methods data
                $paymentData = $fallback['payment'];
                try {
                    $paymentData = $this->buildPaymentMethodsData();
                } catch (\Throwable $e) {
                    $this->recordDashboardError('payment_mix', $e);
                }

                // Inventory chart data
                $inventoryData = $fallback['inventory'];
                try {
                    $inventoryData = $this->buildInventoryChartData();
                } catch (\Throwable $e) {
                    $this->recordDashboardError('inventory_chart', $e);
                }

                return [
                    'sales' => $salesData,
                    'payment' => $paymentData,
                    'inventory' => $inventoryData,
                ];
            });
        } catch (\Throwable $e) {
            $this->recordDashboardError('chart_data', $e);
            $chartData = $fallback;
        }

        $this->salesChartData = $chartData['sales'] ?? $fallback['sales'];
        $this->paymentMethodsData = $chartData['payment'] ?? $fallback['payment'];
        $this->inventoryChartData = $chartData['inventory'] ?? $fallback['inventory'];
    }

    /**
     * Build sales chart data for last 7 days using optimized single query
     */
    protected function buildSalesChartData(): array
    {
        $startDate = now()->subDays(6)->startOfDay();
        $endDate = now()->endOfDay();

        // V30-CRIT-01 FIX: Use sale_date (business date) instead of created_at
        // Single query with GROUP BY to get all 7 days' sales data
        $query = $this->scopeQueryToBranch(Sale::query());
        $salesByDate = $query
            ->whereBetween('sale_date', [$startDate, $endDate])
            ->selectRaw('DATE(sale_date) as business_date, SUM(total_amount) as total')
            ->groupByRaw('DATE(sale_date)')
            ->pluck('total', 'business_date')
            ->toArray();

        $labels = [];
        $data = [];

        // Build the 7-day array, filling in zeros for missing dates
        for ($i = 6; $i >= 0; $i--) {
            $date = now()->subDays($i);
            $dateKey = $date->format('Y-m-d');
            $labels[] = $date->format('D');
            $data[] = decimal_float($salesByDate[$dateKey] ?? 0);
        }

        return ['labels' => $labels, 'data' => $data];
    }

    /**
     * Build payment methods distribution data
     * V30-CRIT-01 FIX: Use sale_date (business date) instead of created_at
     */
    protected function buildPaymentMethodsData(): array
    {
        $raw = DB::table('sale_payments')
            ->join('sales', 'sale_payments.sale_id', '=', 'sales.id')
            ->whereYear('sales.sale_date', now()->year)
            ->whereMonth('sales.sale_date', now()->month)
            ->when(! $this->isAdmin && $this->branchId, fn ($q) => $q->where('sales.branch_id', $this->branchId))
            ->whereNull('sales.deleted_at')
            ->select('sale_payments.payment_method', DB::raw('COUNT(*) as count'), DB::raw('SUM(sale_payments.amount) as total'))
            ->groupBy('sale_payments.payment_method')
            ->get();

        return [
            'labels' => $raw->pluck('payment_method')->map(fn ($m) => ucfirst($m ?? 'cash'))->toArray(),
            'data' => $raw->pluck('count')->toArray(),
            'totals' => $raw->pluck('total')->toArray(),
        ];
    }

    /**
     * Build inventory status chart data using single optimized query
     * V27-CRIT-01 FIX: Use branch-scoped stock calculation instead of global
     *
     * SECURITY NOTE: The $stockExpr is generated by StockService::get*StockCalculationExpression()
     * which validates all column names against SQL injection using regex patterns.
     * The CASE expressions use only hardcoded column names and validated expressions.
     */
    protected function buildInventoryChartData(): array
    {
        $branchFilter = (! $this->isAdmin && $this->branchId) ? $this->branchId : null;

        // V27-CRIT-01 FIX: Use branch-scoped stock calculation when branch context is available
        // SECURITY: StockService validates column names with regex before interpolation
        // @security-reviewed V43 - $stockExpr is validated by StockService regex patterns
        $stockExpr = $branchFilter
            ? StockService::getBranchStockCalculationExpression('products.id', $branchFilter)
            : StockService::getStockCalculationExpression();

        // Single query with CASE expressions for all inventory stats
        // SECURITY: $stockExpr is validated by StockService, other columns are hardcoded
        // @phpstan-ignore-next-line - $stockExpr is regex-validated by StockService
        $result = DB::table('products')
            ->whereNull('deleted_at')
            ->when($branchFilter, fn ($q) => $q->where('branch_id', $branchFilter))
            ->selectRaw("
                SUM(CASE WHEN ({$stockExpr}) > COALESCE(min_stock, 0) THEN 1 ELSE 0 END) as in_stock,
                SUM(CASE WHEN min_stock IS NOT NULL AND min_stock > 0 AND ({$stockExpr}) <= min_stock AND ({$stockExpr}) > 0 THEN 1 ELSE 0 END) as low_stock,
                SUM(CASE WHEN ({$stockExpr}) <= 0 THEN 1 ELSE 0 END) as out_of_stock
            ")
            ->first();

        return [
            'labels' => [__('In Stock'), __('Low Stock'), __('Out of Stock')],
            'data' => [
                (int) ($result->in_stock ?? 0),
                (int) ($result->low_stock ?? 0),
                (int) ($result->out_of_stock ?? 0),
            ],
        ];
    }

    /**
     * Load low stock products
     * V27-CRIT-01 FIX: Use branch-scoped stock calculation instead of global
     *
     * SECURITY NOTE: The $stockExpr is generated by StockService::get*StockCalculationExpression()
     * which validates all column names against SQL injection using regex patterns.
     */
    protected function loadLowStockProducts(): void
    {
        $cacheKey = "{$this->getCachePrefix()}:low_stock";

        try {
            $this->lowStockProducts = Cache::remember($cacheKey, $this->cacheTtl, function () {
                // V27-CRIT-01 FIX: Use branch-scoped stock calculation when branch context is available
                // SECURITY: StockService validates column names with regex before interpolation
                // @security-reviewed V43 - $stockExpr is generated by StockService which validates
                // all inputs via regex pattern /^[a-zA-Z_][a-zA-Z0-9_]*(\.[a-zA-Z_][a-zA-Z0-9_]*)?$/
                $stockExpr = $this->branchId
                    ? StockService::getBranchStockCalculationExpression('products.id', $this->branchId)
                    : StockService::getStockCalculationExpression();

                // @phpstan-ignore-next-line - $stockExpr is regex-validated by StockService
                return $this->scopeQueryToBranch(Product::query())
                    ->select('products.*')
                    ->selectRaw("{$stockExpr} as current_quantity")
                    ->with('category')
                    ->whereRaw("{$stockExpr} <= products.min_stock")
                    ->where('products.min_stock', '>', 0)
                    ->where('products.track_stock_alerts', true)
                    ->orderByRaw($stockExpr)
                    ->limit(5)
                    ->get()
                    ->map(fn ($p) => [
                        'id' => $p->id,
                        'name' => $p->name,
                        'quantity' => $p->current_quantity ?? 0,
                        'min_stock' => $p->min_stock,
                        'category' => $p->category?->name ?? '-',
                    ])
                    ->toArray();
            });
        } catch (\Throwable $e) {
            $this->recordDashboardError('low_stock', $e);
            $this->lowStockProducts = [];
        }
    }

    /**
     * Load recent sales
     */
    protected function loadRecentSales(): void
    {
        $cacheKey = "{$this->getCachePrefix()}:recent_sales";

        try {
            $this->recentSales = Cache::remember($cacheKey, 60, function () {
                return $this->scopeQueryToBranch(Sale::query())
                    // Sale model uses `customer` + `createdBy` (not `user`)
                    ->with(['customer', 'createdBy'])
                    // V30-CRIT-01 FIX: Order by business date (sale_date) first
                    ->orderByDesc('sale_date')
                    ->orderByDesc('id')
                    ->limit(5)
                    ->get()
                    ->map(fn ($s) => [
                        'id' => $s->id,
                        'reference' => $s->reference_number ?? "#{$s->id}",
                        'customer' => $s->customer?->name ?? __('Walk-in'),
                        'total' => number_format((float) ($s->total_amount ?? 0), 2),
                        'status' => $s->status,
                        // Prefer business date; fall back to created_at for legacy records
                        'date' => ($s->sale_date?->format('Y-m-d') ?? $s->created_at?->format('Y-m-d H:i')) ?: '-',
                        'created_by' => $s->createdBy?->name ?? __('System'),
                    ])
                    ->toArray();
            });
        } catch (\Throwable $e) {
            $this->recordDashboardError('recent_sales', $e);
            $this->recentSales = [];
        }
    }

    /**
     * Load trend indicators
     * V30-CRIT-01 FIX: Use sale_date (business date) instead of created_at
     */
    protected function loadTrendIndicators(): void
    {
        $cacheKey = "{$this->getCachePrefix()}:trends";

        try {
            $this->trendIndicators = Cache::remember($cacheKey, $this->cacheTtl, function () {
                $salesQuery = $this->scopeQueryToBranch(Sale::query());

                $currentWeekSales = (clone $salesQuery)
                    ->whereBetween('sale_date', [now()->startOfWeek(), now()->endOfWeek()])
                    ->sum('total_amount') ?? 0;

                $previousWeekSales = (clone $salesQuery)
                    ->whereBetween('sale_date', [now()->subWeek()->startOfWeek(), now()->subWeek()->endOfWeek()])
                    ->sum('total_amount') ?? 0;

                $invoiceBase = (clone $salesQuery)
                    ->whereNotIn('status', SaleStatus::nonRevenueStatuses());

                $invoiceTotal = (clone $invoiceBase)->count();
                $invoiceCleared = (clone $invoiceBase)
                    ->where('payment_status', 'paid')
                    ->count();

                return [
                    'weekly_sales' => [
                        'current' => number_format($currentWeekSales, 2),
                        'previous' => number_format($previousWeekSales, 2),
                        'change' => $this->calculatePercentChange((float) $currentWeekSales, (float) $previousWeekSales),
                    ],
                    'invoice_clear_rate' => $invoiceTotal > 0 ? round(($invoiceCleared / $invoiceTotal) * 100, 1) : 0,
                    'inventory_health' => ($this->stats['total_products'] ?? 0) > 0
                        ? round(max(0, min(100, 100 - ((($this->stats['low_stock_count'] ?? 0) / ($this->stats['total_products'] ?? 1)) * 100))), 1)
                        : 100,
                ];
            });
        } catch (\Throwable $e) {
            $this->recordDashboardError('trends', $e);
            $this->trendIndicators = [
                'weekly_sales' => ['current' => '0.00', 'previous' => '0.00', 'change' => 0.0],
                'invoice_clear_rate' => 0,
                'inventory_health' => 100,
            ];
        }
    }

    /**
     * Calculate percentage change between two values
     */
    protected function calculatePercentChange(float $current, float $previous): float
    {
        if ($previous <= 0 && $current > 0) {
            return 100.0;
        }
        if ($previous === 0.0) {
            return 0.0;
        }

        return round((($current - $previous) / $previous) * 100, 1);
    }
}
